user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}


http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server_tokens off;

  ###########################################
  ### Security Headers
  ###########################################
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

  add_header Content-Security-Policy "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests";

  add_header X-XSS-Protection "1; mode=block";

  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-Content-Type-Options "nosniff";

  add_header Referrer-Policy "no-referrer";

  add_header Cross-Origin-Embedder-Policy "require-corp";
  add_header Cross-Origin-Opener-Policy "same-origin";
  add_header Cross-Origin-Resource-Policy "same-origin";
  add_header X-DNS-Prefetch-Control "off";
  add_header Expect-CT "max-age=0";
  add_header X-Download-Options "noopen";
  add_header Origin-Agent-Cluster "?1";
  add_header X-Permitted-Cross-Domain-Policies "none";
  add_header vary "Origin";
  # add_header Access-Control-Allow-Origin "*";
  add_header Access-Control-Allow-Origin "*" always;

  log_format main '$remote_addr'
                  ' [$time_local]'
                  ' "$request"'
                  ' Status: $status $body_bytes_sent bytes'
                  ' User-Agent: "$http_user_agent"'
                  ' in $request_time s';

  access_log /var/log/nginx/access.log main;

  sendfile on;
  #tcp_nopush     on;

  keepalive_timeout 65;

  gzip  on;

  ### Upstreams
  upstream app {
    server app:1984;
  }

  ### HTTP Server (Redirect all traffic to HTTPS)
  server {
    listen 80 default_server;
    server_name integrador.servehttp.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name integrador.servehttp.com;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/integrador.servehttp.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/integrador.servehttp.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://app;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }

    location /authorization/authorize-request {
      internal;
      proxy_pass http://app;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_pass_request_headers off;
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Original-Method $request_method;
      proxy_set_header Authorization $http_authorization;
    }
  }
}
